# permissions for end users to edit amfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: amf-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: amf-operator
    app.kubernetes.io/part-of: amf-operator
    app.kubernetes.io/managed-by: kustomize
  name: amf-editor-role
rules:
- apiGroups:
  - fiveg.kt.com
  resources:
  - amfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fiveg.kt.com
  resources:
  - amfs/status
  verbs:
  - get
