apiVersion: v1
kind: Service
metadata:
  name: access-core-amf
  namespace: 5gc-amf
  labels:
    app: amf1
spec:
  selector:
    app: amf1
  ports:
    - name: http2
      port: 80
      targetPort: 80

