apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf1
  namespace: 5gc-amf
spec:
  selector:
    matchLabels:
      app: amf1
  replicas: 1
  template:
    metadata:
      labels:
        app: amf1
      annotations:
        k8s.v1.cni.cncf.io/networks: eno3-amf
    spec:
      hostname: amf1
      containers:
      - name: amf1-container
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/root/run/start.sh; while true; do sleep 100000; done;" ]
        image: private.el:5000/amf:0.0.6
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: amf-run
            mountPath: /root/run/
          - name: amf-log
            mountPath: /AMF/log
          - name: 5gc-license
            mountPath: /lib/5gc-license
      volumes:
      - name: amf-run
        configMap:
          name: amf-run
          defaultMode: 0770
      - name: amf-log
        hostPath:
          path: /root/asu/log/AMF
      - name: 5gc-license
        hostPath:
          path: /lib/5gc-license

