apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eno3-amf
  namespace: 5gc-amf
spec:
  config: '{
     "cniVersion": "0.3.1",
     "type": "macvlan",
     "master": "eno3",
     "mode": "bridge",
     "ipam": {
       "type": "static",
       "addresses": [{
               "address": "192.168.10.32/24"
       }],
       "routes": [
                   { "dst": "10.100.60.0/24", "gw": "192.168.10.254" },
                   { "dst": "192.168.30.0/24", "gw": "192.168.10.254" }
       ]
     }
 }'

