apiVersion: v1
kind: Service
metadata:
  name: access-core-amf-svc
  namespace: 5gc-amf
  labels:
    app: amf1
spec:
  type: NodePort
  ports:
    - name: amf-sctp
      port: 38412
      targetPort: 38412
      nodePort: 38412
      protocol: SCTP
  selector:
    app: amf1

